<?php
return [
    'admin.email'       => 'javanshir.abishov@gmail.com',
    //'system.email'      => 'noreply.etibb@gmail.com',
    'system.email'      => 'no-reply@e-tibb.az',
    'site.name'         => 'E-tibb.az',
    'site.url'          => (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]/",//"https://e-tibb.az/", //(isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && (strtolower($_SERVER['HTTPS']) != 'off')?"https://{$_SERVER['SERVER_NAME']}/":"https://{$_SERVER['SERVER_NAME']}/"),
    'site.title'        => 'E-tibb.az',
    'site.description'  => 'Azərbaycanın ən böyük həkim və tibb mərkəzi axtarış kataloqu olan www.e-tibb.az layihəsi səhiyyə və tibb sahəsi üzrə xidmət göstərir',
    'current.date'      => date('Y-m-d'),
    'current.time'      => date('H:i'),
    'path.upload'       => Yii::getAlias('@root').'\upload',
    'site.not_found'    => 'Qeyd olunmayıb',
    'site.defaultThumb' => 'assets/img/no-object.jpg',
    'site.defaultThumb1'=> 'assets/img/no-object1.jpg',
    'site.defaultThumbDoctor'=> 'assets/img/no-doctor.png',
    'site.defaultThumbDoctorF'=> 'assets/img/female.jpg',
    'news.defaultPhoto' => 'no-news.jpg',
    'news.defaultThumb' => 'no-news-s.jpg',
    'path.news'         => 'news',
    'path.enterprises'  => 'enterprises',
    'path.spec'         => 'specialists',
    'path.doctor'       => 'doctors',
    'path.ads'          => 'ads',
    'site.news_uri'     => 'xeberler',
    'site.post_uri'     => 'xeber/',
    'site.qanver_uri'     => 'qanver/',
    'site.hospital_doctor_count' => 10,
    'site.hospital_comment_count' => 10,
    'site.consultation_count' => 20,
    "site.enterprise_slug" => "beledci",
    "site.static_slug"  => "static",
    'site.url.object'   => 'beledci/',
    'site.aksiya'       => 'aksiya/',
    'news.not_in'       => [34],
    'search.type'       => 2,
    'site.doctor_comment_count' => 10,

    'payment.mid'       => 'etibb',
    'payment.secret'    => "123456qwerty",
    'payment.production'=> 0,

    'header.tags'               => null,
    'article.schema'            => null,
    'breadcrumb.schema'         => null,
    'organization.schema'       => null,
    'site_navigation.schema'    => null,
    'site_google_searcbox.schema'=> null,
    'seo' => require 'params-seo.php',

    'og_title' => ['property' => 'og:title', 'content' => 'E-tibb.az - Online tibb kataloqu'],
    'og_description' => ['property' => 'og:description', 'content' => 'Azərbaycandakı həkimlər, klinika və apteklərlə bağlı məlumatlar, yüzlərlə həkim haqqında bilgi,tibbi məsləhətlər, həkimlərin bloqları'],
    'og_url' => ['property' => 'og:url', 'content' => '/'],
    'og_image' => ['property' => 'og:image', 'content' => 'image'],
    'og_type' => ['property' => 'og:type', 'content' => 'article'],
    'og_image_width' => ['property' => 'og:image:width', 'content' => 720],
    'og_image_height' => ['property' => 'og:image:height', 'content' => 377],
];
